#!/usr/bin/env bash
set -euo pipefail

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
umask 077

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
TARGET="${1:-}"

fail() {
  echo "macOS updater creation failed: $*" >&2
  exit 1
}

case "$TARGET" in
  aarch64-apple-darwin|x86_64-apple-darwin)
    ;;
  *)
    fail "expected a macOS Rust target"
    ;;
esac

[[ "$(uname -s)" == "Darwin" ]] || fail "this script must run on macOS"
[[ -n "${TAURI_SIGNING_PRIVATE_KEY:-}" ]] ||
  fail "TAURI_SIGNING_PRIVATE_KEY is required"

BUNDLE_ROOT="$PROJECT_ROOT/src-tauri/target/$TARGET/release/bundle"
APP_DIRECTORY="$BUNDLE_ROOT/macos"

shopt -s nullglob
APP_CANDIDATES=("$APP_DIRECTORY"/*.app)
UPDATER_CANDIDATES=("$BUNDLE_ROOT"/macos/*.app.tar.gz)
shopt -u nullglob

[[ "${#APP_CANDIDATES[@]}" -eq 1 ]] ||
  fail "expected exactly one repaired app bundle"
[[ "${#UPDATER_CANDIDATES[@]}" -eq 1 ]] ||
  fail "expected exactly one updater archive generated by Tauri"

APP_PATH="${APP_CANDIDATES[0]}"
UPDATER_PATH="${UPDATER_CANDIDATES[0]}"
TEMP_ARCHIVE="${UPDATER_PATH}.tmp"

codesign --verify --deep --strict --verbose=4 "$APP_PATH"
/usr/bin/tar -czf "$TEMP_ARCHIVE" -C "$APP_DIRECTORY" "$(basename "$APP_PATH")"
/bin/mv -f "$TEMP_ARCHIVE" "$UPDATER_PATH"
/bin/rm -f "${UPDATER_PATH}.sig"

pnpm exec tauri signer sign "$UPDATER_PATH"

[[ -s "${UPDATER_PATH}.sig" ]] || fail "updater signature was not created"

printf 'Updater: %s\n' "$UPDATER_PATH"
printf 'Signature: %s\n' "${UPDATER_PATH}.sig"
printf 'Repaired app signature verification: passed\n'
